### ISSUE TITLE
Access of RDF file via URI

### ISSUE THREAD

**Issue by DonRolph** [labra/rdfshape#20] opened 2016-09-28 16:48 UTC
Ok, next issue.  When I try to access a TTL based RDF file via the uri:

http://operations.refdata.amgen.com/ontology/measurement.ttl

I get the following error:

Exception raised

getURI: cannot retrieve content from http://operations.refdata.amgen.com/ontology/measurement.ttl
Exception: Input length = 1

I can retrieve the TTL file with http://operations.refdata.amgen.com/ontology/measurement.ttl from the operations.refdata.amgen.com server using a web browser.

**Comment by labra** [comment] 2019-04-20 06:26
I close the issue as I can't reproduce it. It seems the http://operations.refdata.amgen.com/ontology/measurement.ttl is not available anymore and anyway, I think it is possible to access data from URLs.

**Closed by labra** 2019-04-20 06:26 UTC
